### ISSUE TITLE
[Feature Request] - Gravity selection on Resize and Crop become a drop down with values

### ISSUE THREAD

**Issue by Jhanlon95** [azuravian/playnite-gamemediaprocessor#2]
I was trying to use Game Media Processor to make full sized images into Steam like banners when trying to use the Resize and Crop tool, it defaults to "Center" for gravity which crops off the top and bottom, where as in the instance I needed it, I only wanted to crop the bottom. I couldn't figure out what values to enter into the Gravity field to do this and had to check inside the code itself to see what the keywords are

Proposal would be to have a drop-down menu with the values that would be used, in this case North, North East etc. Would provide easier selection and would stop confusion

![image](https://user-images.githubusercontent.com/11045596/135596924-07330664-9527-4985-ba88-b00ee6d84b0d.png)

**Comment by azuravian** [comment]
Done in v1.9
