### ISSUE TITLE
[Feature Request] Add Game Media Processor into the right click menu

### ISSUE THREAD

**Issue by Jhanlon95** [azuravian/playnite-gamemediaprocessor#3]
When using the extension you need to select a game -> go to Playnite's menu -> to extensions -> Game Media Tools -> Click on Game Media Processor

Would it be possible to have it appearing within the right click context menu, either as it's own entry in the context or within the Game Media Tools sub-section?

**Comment by azuravian** [comment]
Done in v1.9
