### ISSUE TITLE
Cannot upgrade Game Media Processor add-on to any version after 1.9.0

### ISSUE THREAD

**Issue by cowbutt** [azuravian/playnite-gamemediaprocessor#9]
For some reason, the Game Media Processor add-on won't automatically upgrade from the presently installed version 1.9.0 to either 1.9.5 or 1.9.6. Other add-ons automatically upgrade without any issue. There are no obvious error messages, when installing or restarting Playnite, but the version remains at 1.9.0 with a new version still listed in updates. I've also tried downloading the .pext and dragging it to Playnite, which has the same behaviour.

**Comment by cowbutt** [comment]
Hmm, fixed. Apparently, the new versions were installing, but not replacing the 1.9.0 installation. Perhaps it was the Playnite 8 version hanging around since before updating to a later version of Playnite. I uninstalled the old 1.9.0 version and all appears well.

**Comment by cowbutt** [comment]
Hmm, fixed. Apparently, the new versions were installing, but not replacing the 1.9.0 installation. Perhaps it was the Playnite 8 version hanging around since before updating to a later version of Playnite. I uninstalled the old 1.9.0 version and all appears well.

**Comment by azuravian** [comment]
I think this is because the branch name changed, which meant I had to edit the manifest to point to the new branch name.  Glad you got it sorted.
